databases:
  - name: rails_auth_starter
    databaseName: rails_auth_starter
    user: rails_auth_starter
    plan: free

services:
  - type: web
    name: rails_auth_starter
    runtime: ruby
    plan: free
    buildCommand: "bin/render-build.sh"
      # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_auth_starter
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
